export const LOAD_TOPSALES = 'LOAD_TOPSALES';

export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';

export const LOAD_PAGE_ITEM = 'LOAD_PAGE_ITEM';

export const LOAD_CATALOG_ITEMS = 'LOAD_CATALOG_ITEMS';
export const APPEND_CATALOG_ITEMS = 'APPEND_CATALOG_ITEMS';

export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART';
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART';

export const CLEAR_CART = 'CLEAR_CART';
