export const LOAD_TOPSALES = 'LOAD_TOPSALES';

export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';

export const LOAD_CATALOG_ITEMS = 'LOAD_CATALOG_ITEMS';
export const APPEND_CATALOG_ITEMS = 'APPEND_CATALOG_ITEMS';
