export const TOPSALES_REDUCER = 'TOPSALES';
export const CATEGORIES_REDUCER = 'CATEGORIES';
export const CATALOG_REDUCER = 'CATALOG';
export const LOADEDITEM_REDUCER = 'LOADEDITEM';
export const CHECKOUT_REDUCER = 'CHECKOUT';
